import {
  UserProfile,
  Transaction,
  SavingsGoal,
  Budget,
  AIInsight,
  NotificationItem,
  GoalContribution,
  TransactionCategory,
} from '@/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_001',
  name: 'Samarth Patel',
  email: 'samarth@saveiq.app',
  currency: 'INR',
  currencySymbol: '₹',
  monthlyIncome: 45000,
  defaultSavingsTarget: 30, // 30%
  theme: 'light',
  notificationsEnabled: true,
  budgetAlertsEnabled: true,
  goalMilestoneAlertsEnabled: true,
  joinedDate: '2026-01-15',
};

// Target date reference: 2027
export const INITIAL_GOALS: SavingsGoal[] = [
  {
    id: 'goal_laptop',
    name: 'MacBook / Laptop',
    targetAmount: 120000,
    currentAmount: 72000,
    targetDate: '2027-03-31',
    priority: 'high',
    category: 'Gadget',
    description: 'Apple MacBook Pro M-series for development and creator workflows.',
    color: '#059669', // Emerald
    icon: 'Laptop',
    createdAt: '2026-03-01',
  },
  {
    id: 'goal_emergency',
    name: 'Emergency Fund',
    targetAmount: 100000,
    currentAmount: 65000,
    targetDate: '2027-01-31',
    priority: 'high',
    category: 'Emergency',
    description: '6 months of living expenses reserve in a high-yield savings account.',
    color: '#0284c7', // Sky
    icon: 'ShieldCheck',
    createdAt: '2026-01-15',
  },
  {
    id: 'goal_goa',
    name: 'Goa Trip with Friends',
    targetAmount: 30000,
    currentAmount: 18000,
    targetDate: '2026-12-20',
    priority: 'medium',
    category: 'Travel',
    description: 'Year-end vacation retreat with flight tickets, resort stay, and scooter rental.',
    color: '#f59e0b', // Amber
    icon: 'Palmtree',
    createdAt: '2026-05-10',
  },
  {
    id: 'goal_education',
    name: 'Executive AI Certification',
    targetAmount: 200000,
    currentAmount: 50000,
    targetDate: '2027-08-31',
    priority: 'medium',
    category: 'Education',
    description: 'Post-graduate certification course fees and research project materials.',
    color: '#8b5cf6', // Purple
    icon: 'GraduationCap',
    createdAt: '2026-04-01',
  },
];

export const INITIAL_CONTRIBUTIONS: GoalContribution[] = [
  { id: 'c_01', goalId: 'goal_laptop', amount: 8000, date: '2026-09-02', note: 'Monthly goal transfer' },
  { id: 'c_02', goalId: 'goal_laptop', amount: 8000, date: '2026-08-02', note: 'Monthly goal transfer' },
  { id: 'c_03', goalId: 'goal_emergency', amount: 5000, date: '2026-09-05', note: 'Automated sweep' },
  { id: 'c_04', goalId: 'goal_goa', amount: 3000, date: '2026-09-12', note: 'Weekend savings match' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_salary',
    merchant: 'Salary Credit - TechCorp',
    amount: 45000,
    type: 'income',
    category: 'Income',
    date: '2026-09-01',
    paymentMethod: 'Net Banking',
    notes: 'Monthly regular employment salary',
    createdAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tx_swiggy_1',
    merchant: 'Swiggy',
    amount: 480,
    type: 'expense',
    category: 'Food',
    date: '2026-09-03',
    paymentMethod: 'UPI',
    notes: 'Dinner gourmet bowl',
    createdAt: '2026-09-03T20:15:00Z',
  },
  {
    id: 'tx_amazon_1',
    merchant: 'Amazon India',
    amount: 2999,
    type: 'expense',
    category: 'Shopping',
    date: '2026-09-05',
    paymentMethod: 'Credit Card',
    notes: 'Wireless ergonomic keyboard & desk mat',
    createdAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'tx_uber_1',
    merchant: 'Uber',
    amount: 320,
    type: 'expense',
    category: 'Transport',
    date: '2026-09-07',
    paymentMethod: 'UPI',
    notes: 'Commute to coworking tech hub',
    createdAt: '2026-09-07T09:45:00Z',
  },
  {
    id: 'tx_netflix',
    merchant: 'Netflix',
    amount: 649,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-09-08',
    paymentMethod: 'Credit Card',
    notes: 'Premium 4K monthly recurring plan',
    createdAt: '2026-09-08T06:00:00Z',
  },
  {
    id: 'tx_electricity',
    merchant: 'Electricity BESCOM',
    amount: 1850,
    type: 'expense',
    category: 'Bills',
    date: '2026-09-10',
    paymentMethod: 'Net Banking',
    notes: 'Utility electricity bill for apartment',
    createdAt: '2026-09-10T11:20:00Z',
  },
  {
    id: 'tx_zomato_1',
    merchant: 'Zomato',
    amount: 650,
    type: 'expense',
    category: 'Food',
    date: '2026-09-12',
    paymentMethod: 'UPI',
    notes: 'Sunday family lunch order',
    createdAt: '2026-09-12T13:40:00Z',
  },
  {
    id: 'tx_flipkart',
    merchant: 'Flipkart',
    amount: 1450,
    type: 'expense',
    category: 'Shopping',
    date: '2026-09-14',
    paymentMethod: 'UPI',
    notes: 'Fitness resistance bands and water bottle',
    createdAt: '2026-09-14T16:10:00Z',
  },
  {
    id: 'tx_airtel',
    merchant: 'Airtel Broadband',
    amount: 999,
    type: 'expense',
    category: 'Bills',
    date: '2026-09-15',
    paymentMethod: 'Credit Card',
    notes: 'Airtel Xstream Fiber 200Mbps',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'tx_ola',
    merchant: 'Ola Cabs',
    amount: 280,
    type: 'expense',
    category: 'Transport',
    date: '2026-09-16',
    paymentMethod: 'UPI',
    notes: 'Evening ride return',
    createdAt: '2026-09-16T19:30:00Z',
  },
  {
    id: 'tx_spotify',
    merchant: 'Spotify India',
    amount: 119,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-09-18',
    paymentMethod: 'UPI',
    notes: 'Individual premium student/standard plan',
    createdAt: '2026-09-18T08:15:00Z',
  },
  {
    id: 'tx_grocery',
    merchant: 'Reliance Smart / Nature Basket',
    amount: 3670,
    type: 'expense',
    category: 'Food',
    date: '2026-09-19',
    paymentMethod: 'Debit Card',
    notes: 'Bi-weekly staples, milk, fruits, veggies',
    createdAt: '2026-09-19T17:00:00Z',
  },
  {
    id: 'tx_amazon_2',
    merchant: 'Amazon India',
    amount: 1751,
    type: 'expense',
    category: 'Shopping',
    date: '2026-09-22',
    paymentMethod: 'Credit Card',
    notes: 'Casual cotton shirts and socks bundle',
    createdAt: '2026-09-22T15:20:00Z',
  },
  {
    id: 'tx_pharmacy',
    merchant: 'Apollo Pharmacy',
    amount: 820,
    type: 'expense',
    category: 'Healthcare',
    date: '2026-09-24',
    paymentMethod: 'UPI',
    notes: 'Daily vitamins and cold medicine',
    createdAt: '2026-09-24T18:00:00Z',
  },
  {
    id: 'tx_fuel',
    merchant: 'Indian Oil Fuel Station',
    amount: 1500,
    type: 'expense',
    category: 'Transport',
    date: '2026-09-25',
    paymentMethod: 'Credit Card',
    notes: 'Fuel tank refill',
    createdAt: '2026-09-25T11:45:00Z',
  },
  {
    id: 'tx_rent',
    merchant: 'Apartment Maintenance & Water',
    amount: 14612,
    type: 'expense',
    category: 'Bills',
    date: '2026-09-02',
    paymentMethod: 'Net Banking',
    notes: 'Rent and society monthly maintenance',
    createdAt: '2026-09-02T10:00:00Z',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  { id: 'b_food', category: 'Food', monthlyLimit: 6000 },
  { id: 'b_shopping', category: 'Shopping', monthlyLimit: 5000 },
  { id: 'b_transport', category: 'Transport', monthlyLimit: 3000 },
  { id: 'b_bills', category: 'Bills', monthlyLimit: 18000 },
  { id: 'b_entertainment', category: 'Entertainment', monthlyLimit: 2000 },
  { id: 'b_healthcare', category: 'Healthcare', monthlyLimit: 2500 },
  { id: 'b_other', category: 'Other', monthlyLimit: 2000 },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Shopping Budget Alert',
    message: 'Shopping expenses reached ₹6,200, exceeding your ₹5,000 monthly limit by ₹1,200.',
    type: 'warning',
    timestamp: '2026-09-22T15:25:00Z',
    isRead: false,
    link: '/budget',
  },
  {
    id: 'notif_2',
    title: 'Emergency Fund Milestone',
    message: "You've crossed 65% of your Emergency Fund goal! You're on track to complete it by January 2027.",
    type: 'success',
    timestamp: '2026-09-20T10:00:00Z',
    isRead: false,
    link: '/goals',
  },
  {
    id: 'notif_3',
    title: 'Savings Rate Up',
    message: 'Your monthly savings rate reached 30% this month (₹13,500 saved), up from 26% last month.',
    type: 'info',
    timestamp: '2026-09-15T09:00:00Z',
    isRead: true,
    link: '/analytics',
  },
];

export const CATEGORIES: TransactionCategory[] = [
  'Food',
  'Shopping',
  'Transport',
  'Bills',
  'Entertainment',
  'Healthcare',
  'Other',
];

export const CATEGORY_COLORS: Record<TransactionCategory, string> = {
  Income: '#10b981',
  Food: '#f59e0b',
  Shopping: '#ec4899',
  Transport: '#06b6d4',
  Bills: '#6366f1',
  Entertainment: '#8b5cf6',
  Healthcare: '#14b8a6',
  Other: '#64748b',
};
